# Generated by Django 6.0.1 on 2026-01-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostitem',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
